config/routes.rb
Rails.application.routes.draw do
root 'events#index'
get 'events/service', to:'events#service'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  def free?
price.blank? || price.zero?
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def service
  @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def price(event)
    if event.free?
      "Free"
    else
      number_to_currency(event.price, precision: 0)
    end
end
def date_and_time(event)
  event.starts_at.strftime("%B %d at %I:%M %P")
end
end

app/views/events/_header.html.erb
<style>
  body {
  background-color: lightblue;
}
</style>
<nav class="navbar navbar-expand-lg bg-dark">

  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand"> <font color=##FFFF00> <font size = "130">Easy Chinese  </font></font></a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <%= link_to "Головна", root_path, class: "nav-link active"%>
        <%= link_to "Послуги", events_service_path, class: "nav-link active"%>

        <li class="nav-item">
          <a class="nav-link" href="https://instagram.com/easy_chinese._?igshid=YmMyMTA2M2Y=">Instagram</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.facebook.com/easy.chinesee">Facebook</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.tiktok.com/@easychinese_ua?_t=8UQGpjzMojN&_r=1">Tik Tok</a>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/events/index.html.erb
<style>
img {width: 40}

  </style>

<h1> <strong><font color=##800000> Раді вітати кожного на нашій сторінці! </font> </strong>
  </h1>
</br>

  <img src="https://scontent.fhmj1-1.fna.fbcdn.net/v/t39.30808-6/295184275_573241391141213_933793283183827728_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=0Iws9Dd03acAX-X7KhR&_nc_ht=scontent.fhmj1-1.fna&oh=00_AT8VxceuyANhOXm7J4Ch4jfEN7cbtKn9SjQVdNDKMoJgnw&oe=62EA0796" width="800" height="600">
<p> <font color=##800000> <font size = "50"> Допоможемо вам швидко, а головне цікаво опанувати або ж екзотичну китайську, або ж всюди потрібну англійську! </font> </font> </p>

app/views/events/service.html.erb
<header>  <font color=##0000FF> <font size = "100>"<strong>НАШІ ПОСЛУГИ </strong>  </font> </font>
 </header>
 <br/>
 <ul>
 <%@events.each do |event|%>
 <li>
   <font color=##800000>  <font size = "90"
   <strong><%=event.name%></strong>
   in <%= event.location %>:
   <%= price(event)%>
   </font>
   </font>
   </li>
   <p>
     <%= truncate(event.description, length: 35, separator: '') %>
     </p>
   <p>
     <font color=##0000FF> <font size = "60">
   Найближча вільна дата: <%= date_and_time(event) %> </font> </font>
     </p>
 <%end%>
 </ul>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Easy Chinese</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  <body>
    <%=render 'events/header'%>
    <div class = 'container'>
      <br/>
    <%= yield %>
    <div/>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>